---
- name: Install and configure Nginx
  hosts: localhost
  become: yes
  vars:
    nginx_index_content: |
      <html>
        <head><title>Welcome to Nginx!</title></head>
        <body>
          <h1>Hello, Ansible is successfully installed!</h1>
          <p>This page is served by Nginx on an EC2 instance.</p>
        </body>
      </html>

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy custom index.html to Nginx's web root
      copy:
        dest: /var/www/html/index.html
        content: "{{ nginx_index_content }}"
      notify: restart nginx

    - name: Allow HTTP traffic through UFW
      ufw:
        rule: allow
        name: 'Nginx Full'
      when: ansible_distribution == "Ubuntu"

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
