#!/bin/bash

echo -n "Enter first digit: "
read le
echo -n "Enter last digit: "
read ri

is_prime() {
    if [ $1 -lt 2 ]; then
        return 1
    fi

    ctr=0
    for ((i=2; i<$1; i++)); do
        if [ $(( $1 % i )) -eq 0 ]; then
            ctr=$((ctr+1))
        fi
    done

    if [ $ctr -eq 0 ]; then
        printf "%d " "$1"
    fi
}

printf "Prime numbers between %d and %d are: " "$le" "$ri"
for ((i=le; i<=ri; i++)); do
    is_prime $i
done
printf "\n"
