#!/bin/bash

# URL to be pinged
URL="http URL"

# Send a request to the URL and get the HTTP status code
HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" "$URL")

# Display the status
if [ "$HTTP_STATUS" -eq 200 ]; then
    echo "URL is reachable. Status: $HTTP_STATUS"
else
    echo "URL is not reachable. Status: $HTTP_STATUS"
fi


For loop for multiple server

REMOTE_SERVER=("www.guvi.in" "www.flipkart.com" "walle")

PING_COUNT=4

for SERVER in "${REMOTE_SERVER[@]}"; do
        echo "Pinging $SERVER ...."

        ping -c "$PING_COUNT" "$SERVER" > /dev/null 2>&1

        if [ $? -eq 0 ]; then
                echo "SERVER $SERVER is reachable"
        else
                echo "SERVER $SERVER is not reachable"
                echo "Running brew update for $SERVER ..."
                brew update
                if [ $? -eq 0 ]; then
                        echo "brew update successful"
                else
                        echo "brew update failed"
                fi
        fi
        echo ""
done
